<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kf_mobile_de"
 *
 * Auto generated by Extension Builder 2021-12-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'KF - Mobile.de',
    'description' => 'a plugin to show the mobile.de data in typo3',
    'category' => 'plugin',
    'author' => 'Marc Finnern',
    'author_email' => 'typo3@klickfabrik.net',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-11.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
